Profile/Controllers/DetailProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using Model.EF;

namespace Profile.Controllers
{
    public class DetailProductsController : Controller
    {
        // GET: DetailProducts
        [HttpGet]
        public ActionResult Single()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Detail()
        {
            var dao = new ProductsDao();
            var list = dao.ListProducts();
            return View(list);
        }
        //[HttpGet]
        //public ActionResult Detail( long id)
        //{
        //    var dao = new ProductsDao().GetDetail(id);
        //    return View(dao);
        //}
    }
}

Profile/Views/Shared/MenuNavigation.cshtml
@model List<Model.EF.Menu>

<div class="ban-top">
    <div class="container">
        <div class="agileits-navi_search">
            <form action="#" method="post">
                <select id="agileinfo-nav_search" name="agileinfo_search" required="">
                    <option value="">All Categories</option>
                    <option value="Kitchen">Kitchen</option>
                    <option value="Household">Household</option>
                    <option value="Snacks &amp; Beverages">Snacks & Beverages</option>
                    <option value="Personal Care">Personal Care</option>
                    <option value="Gift Hampers">Gift Hampers</option>
                    <option value="Fruits &amp; Vegetables">Fruits & Vegetables</option>
                    <option value="Baby Care">Baby Care</option>
                    <option value="Soft Drinks &amp; Juices">Soft Drinks & Juices</option>
                    <option value="Frozen Food">Frozen Food</option>
                    <option value="Bread &amp; Bakery">Bread & Bakery</option>
                    <option value="Sweets">Sweets</option>
                </select>
            </form>
        </div>
        <div class="top_nav_left">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                                aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav menu__list">
                            @foreach (var item in Model)
                            {
                                if (item.TypeID == 1)
                                {

                                    if (item.Text == "Kitchen")
                                    {
                                        //Url Kitchen
                                        <li class="dropdown">
                                            <a class="nav-stylehead" href="@Url.Action("Single","DetailProducts")" @*href="@item.Link"*@ target="@item.Target">
                                                @item.Text
                                            </a>



                                        </li>
                                    }
                                    @*Url HouseHold*@
                                    else if (item.Text == "HouseHold")
                                    {
                                        <li>
                                            <a class="nav-stylehead" href="@Url.Action("Detail","DetailProducts")" @*href="@item.Link"*@ target="@item.Target">
                                                @item.Text
                                            </a>
                                        </li>
                                    }
                                    else
                                    {
                                        <li>
                                            <a class="nav-stylehead" href="@item.Link" target="@item.Target">
                                                @item.Text
                                            </a>
                                        </li>
                                }


                            }
                            @*if (item.TypeID == 13)
                            {
                                <li>
                                    <ul class="multi-column-dropdown">
                                        <li>
                                            <a href="@item.Target">@item.Text + @item.ID</a>
                                        </li>
                                    </ul>
                                </li>
                                }*@
                            }
                          
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

Profile/Views/Shared/Slide.cshtml
 
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
        <li data-target="#myCarousel" data-slide-to="3" class=""></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="container">
                <div class="carousel-caption">
                    <h3>
                        Big
                        <span>Save</span>
                    </h3>
                    <p>
                        Get flat
                        <span>10%</span> Cashback
                    </p>
                    <a class="button2" href="product.html">Shop Now </a>
                </div>
            </div>
        </div>
        <div class="item item2">
            <div class="container">
                <div class="carousel-caption">
                    <h3>
                        Healthy
                        <span>Saving</span>
                    </h3>
                    <p>
                        Get Upto
                        <span>30%</span> Off
                    </p>
                    <a class="button2" href="product.html">Shop Now </a>
                </div>
            </div>
        </div>
        <div class="item item3">
            <div class="container">
                <div class="carousel-caption">
                    <h3>
                        Big
                        <span>Deal</span>
                    </h3>
                    <p>
                        Get Best Offer Upto
                        <span>20%</span>
                    </p>
                    <a class="button2" href="product.html">Shop Now </a>
                </div>
            </div>
        </div>
        <div class="item item4">
            <div class="container">
                <div class="carousel-caption">
                    <h3>
                        Today
                        <span>Discount</span>
                    </h3>
                    <p>
                        Get Now
                        <span>40%</span> Discount
                    </p>
                    <a class="button2" href="product.html">Shop Now </a>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Profile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vn">

<head>
    <title>Grocery Shoppy</title>
    <!--/tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Grocery Shoppy Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
    </script>
    <!--//tags -->
    <link href="~/Areas/Client/main_css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Areas/Client/main_css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Areas/Client/main_css/font-awesome.css" rel="stylesheet">
    <!--pop-up-box-->
    <link href="~/Areas/Client/main_css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
    <!--//pop-up-box-->
    <!-- price range -->
    <link rel="stylesheet" type="text/css" href="~/Areas/Client/main_css/jquery-ui1.css">
    <!-- fonts -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
    <!-- jquery -->
    <script src="~/Areas/Client/main_js/jquery-2.1.4.min.js"></script>
    <script src="~/Areas/Client/main_js/jquery-ui.js"></script>
</head>

<body>
    @Html.Partial("MenuTop")
    <!-- signin Model -->
    <script src="~/Areas/Client/main_js/jquery.magnific-popup.js"></script>
    <script>
		$(document).ready(function () {
			$('.popup-with-zoom-anim').magnificPopup({
				type: 'inline',
				fixedContentPos: false,
				fixedBgPos: true,
				overflowY: 'auto',
				closeBtnInside: true,
				preloader: false,
				midClick: true,
				removalDelay: 300,
				mainClass: 'my-mfp-zoom-in'
			});

		});
    </script>
    <!-- Modal1 -->
    <div class="modal fade" id="myModal1" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body modal-body-sub_agile">
                    <div class="main-mailposi">
                        <span class="fa fa-envelope-o" aria-hidden="true"></span>
                    </div>
                    <div class="modal_body_left modal_body_left1">
                        <h3 class="agileinfo_sign">Sign In </h3>
                        <p>
                            Sign In now, Let's start your Grocery Shopping. Don't have an account?
                            <a href="#" data-toggle="modal" data-target="#myModal2">
                                Sign Up Now
                            </a>
                        </p>
                        <form action="#" method="post">
                            <div class="styled-input agile-styled-input-top">
                                <input type="text" placeholder="User Name" name="Name" required="">
                            </div>
                            <div class="styled-input">
                                <input type="password" placeholder="Password" name="password" required="">
                            </div>
                            <input type="submit" value="Sign In">
                        </form>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <!-- //Modal content-->
        </div>
    </div>
    <!-- //Modal1 -->
    <!-- //signin Model -->
    <!-- signup Model -->
    <!-- Modal2 -->
    <div class="modal fade" id="myModal2" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body modal-body-sub_agile">
                    <div class="main-mailposi">
                        <span class="fa fa-envelope-o" aria-hidden="true"></span>
                    </div>
                    <div class="modal_body_left modal_body_left1">
                        <h3 class="agileinfo_sign">Sign Up</h3>
                        <p>
                            Come join the Grocery Shoppy! Let's set up your Account.
                        </p>
                        <form action="#" method="post">
                            <div class="styled-input agile-styled-input-top">
                                <input type="text" placeholder="Name" name="Name" required="">
                            </div>
                            <div class="styled-input">
                                <input type="email" placeholder="E-mail" name="Email" required="">
                            </div>
                            <div class="styled-input">
                                <input type="password" placeholder="Password" name="password" id="password1" required="">
                            </div>
                            <div class="styled-input">
                                <input type="password" placeholder="Confirm Password" name="Confirm Password" id="password2" required="">
                            </div>
                            <input type="submit" value="Sign Up">
                        </form>
                        <p>
                            <a href="#">By clicking register, I agree to your terms</a>
                        </p>
                    </div>
                </div>
            </div>
            <!-- //Modal content-->
        </div>
    </div>
    <!-- //Modal2 -->
    <!-- //signup Model -->
    <!-- //header-bot -->
    <!-- navigation -->
    @{Html.RenderAction("MenuNavigation", "Home");}
   @*@Html.Partial("MenuNavigation")*@
    <!-- //navigation -->
    <!-- banner -->
    @Html.Partial("Slide")
    <!-- //banner -->
    @*---------*@
    <!-- top Products -->
    @RenderBody()
    <!-- //top products -->
    <!-- special offers -->
    
    <!-- //special offers -->
    @*---------*@
    <!-- footer top and bottem -->
    @Html.Partial("Footer")
    <!-- //footer -->
    <!-- js-files --> 
    <!-- //jquery -->
    <!-- popup modal (for signin & signup)-->
   
    <!-- Large modal -->
    <!-- <script>
        $('#').modal('show');
    </script> -->
    <!-- //popup modal (for signin & signup)-->
    <!-- cart-js -->
    <script src="~/Areas/Client/main_js/minicart.js"></script>
    <script>
		paypalm.minicartk.render(); //use only unique class names other than paypalm.minicartk.Also Replace same class name in css and minicart.min.js

		paypalm.minicartk.cart.on('checkout', function (evt) {
			var items = this.items(),
				len = items.length,
				total = 0,
				i;

			// Count the number of each item in the cart
			for (i = 0; i < len; i++) {
				total += items[i].get('quantity');
			}

			if (total < 3) {
				alert('The minimum order quantity is 3. Please add more to your shopping cart before checking out');
				evt.preventDefault();
			}
		});
    </script>
    <!-- //cart-js -->
    <!-- price range (top products) -->
    @*<script src="~/Areas/Client/main_js/jquery-ui.js"></script>*@
    <script>
		//<![CDATA[
		$(window).load(function () {
			$("#slider-range").slider({
				range: true,
				min: 0,
				max: 9000,
				values: [50, 6000],
				slide: function (event, ui) {
					$("#amount").val("$" + ui.values[0] + " - $" + ui.values[1]);
				}
			});
			$("#amount").val("$" + $("#slider-range").slider("values", 0) + " - $" + $("#slider-range").slider("values", 1));

		}); //]]>
    </script>
    <!-- //price range (top products) -->
    <!-- flexisel (for special offers) -->
    <script src="~/Areas/Client/main_js/jquery.flexisel.js"></script>
    <script>
		$(window).load(function () {
			$("#flexiselDemo1").flexisel({
				visibleItems: 3,
				animationSpeed: 1000,
				autoPlay: true,
				autoPlaySpeed: 3000,
				pauseOnHover: true,
				enableResponsiveBreakpoints: true,
				responsiveBreakpoints: {
					portrait: {
						changePoint: 480,
						visibleItems: 1
					},
					landscape: {
						changePoint: 640,
						visibleItems: 2
					},
					tablet: {
						changePoint: 768,
						visibleItems: 2
					}
				}
			});

		});
    </script>
    <!-- //flexisel (for special offers) -->
    <!-- password-script -->
    <script>
		window.onload = function () {
			document.getElementById("password1").onchange = validatePassword;
			document.getElementById("password2").onchange = validatePassword;
		}

		function validatePassword() {
			var pass2 = document.getElementById("password2").value;
			var pass1 = document.getElementById("password1").value;
			if (pass1 != pass2)
				document.getElementById("password2").setCustomValidity("Passwords Don't Match");
			else
				document.getElementById("password2").setCustomValidity('');
			//empty string means no validation error
		}
    </script>
    <!-- //password-script -->
    <!-- smoothscroll -->
    @*<script src="~/Areas/Client/main_js/SmoothScroll.min.js"></script>*@
    <script src="~/Areas/Client/main_js/SmoothScroll.min.js"></script>
    <!-- //smoothscroll -->
    <!-- start-smooth-scrolling -->
    <script src="~/Areas/Client/main_js/move-top.js"></script>
    <script src="~/Areas/Client/main_js/easing.js"></script>
    <script>
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();

				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 1000);
			});
		});
    </script>
    <!-- //end-smooth-scrolling -->
    <!-- smooth-scrolling-of-move-up -->
   
    <script>
		$(document).ready(function () {
			/*
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
			};
			*/
			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
    </script>
    <!-- //smooth-scrolling-of-move-up -->
    <!-- for bootstrap working -->
    @*<script src="~/Areas/Client/main_js/bootstrap.js"></script>*@
    <!-- //for bootstrap working -->
    <!-- //js-files -->
    @RenderSection("script", required: false)
</body>

</html>

Profile/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>


    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/Content/js/plugins/bootstrap/bootstrap.min.css">
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">*@
    <!-- slick slider -->
    @*<link rel="stylesheet" href="~/Content/js/plugins/slick/slick.css">*@
    <link href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.4.1/slick.css" rel="stylesheet" />
    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css" rel="stylesheet" />*@
    <!-- themefy-icon -->
    @*<link rel="stylesheet" href="~/Content/js/plugins/themify-icons/themify-icons.css">*@
    <link href="https://cdn.jsdelivr.net/themify-icons/0.1.2/css/themify-icons.css" rel="stylesheet" />
    <!-- Main Stylesheet -->
    <link href="~/Content/css/styles.css" rel="stylesheet">

</head>
<body>
    <header class="navigation fixed-top nav-bg">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand font-tertiary h3" href="#"><img src="../Content/images/Logo_XP_Template.svg" alt="Phi"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-center" id="navigation">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="index.html">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="blog.html">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="file:///F:/TaiLieuCaNhan/ASP.NET/PROJECTS/Theme/paper-kit-2-html-v2.2.0/paper-kit-2-html-v2.2.0/index.html" target="_blank">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Dashboard", "Home")" target="_blank">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Login")">Log In</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- hero area -->
    @RenderBody()

    <!-- jQuery -->
    <script src="~/Content/js/plugins/jQuery/jquery.min.js"></script>
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>*@

    <!-- Bootstrap JS -->
    <script src="~/Content/js/plugins/bootstrap/bootstrap.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>*@

    <!-- slick slider -->
    @*<script src="~/Content/js/plugins/slick/slick.min.js"></script>*@
    <script src="//cdn.jsdelivr.net/jquery.slick/1.4.1/slick.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"></script>*@

    <!-- filter -->
    <script src="~/Content/js/plugins/shuffle/shuffle.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/Shuffle/5.2.1/shuffle.min.js"></script>*@

    <!-- Main Script -->
    <script src="~/Content/js/script.js"></script>

</body>
</html>